#!/usr/bin/env python3
"""Write `tag ksi:` into the hand-written control files, derived from `tag nist:`.

Why the tags are written into the source rather than computed
------------------------------------------------------------
InSpec collects `tag` values from the AST at PARSE time. A tag whose value is a
method call arrives at the collector as a RuboCop::AST::SendNode and it calls
`.value` on it:

    undefined method 'value' for an instance of RuboCop::AST::SendNode

That aborts `check` for the whole profile. So this cannot be a runtime lookup,
however much tidier that would read. It has to be a literal in the file, which
means something has to put it there and something has to prove it stayed
correct. This script is both: it rewrites in place, and `--check` fails when the
file disagrees with the mapping.

Scope
-----
The hand-written control files only. `controls/coverage.rb` is generated by
tools/render_controls.py, which emits its own KSI tags through the same
resolver — rewriting it here would put the two generators in a fight, each
undoing the other, and `--check` would flap depending on run order.

It also renders the generated block in docs/ksi_coverage.md, from the same
resolution, so the documented coverage and the emitted tags cannot disagree.

Usage:
    python3 tools/render_ksi.py            # rewrite in place
    python3 tools/render_ksi.py --check    # exit 1 if anything is stale
"""

from __future__ import annotations

import argparse
import collections
import pathlib
import re
import sys

from ksi_resolver import KsiCatalog, tag_lines

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTROLS = ROOT / "controls"
DOC = ROOT / "docs" / "ksi_coverage.md"
DOC_BEGIN = "<!-- BEGIN GENERATED: ksi-coverage -->"
DOC_END = "<!-- END GENERATED: ksi-coverage -->"

# Generated elsewhere from the same resolver. See the module docstring.
GENERATED = {"coverage.rb"}

CONTROL_ID = re.compile(r"^control\s+'([^']+)'\s+do\s*$")
NIST_LINE = re.compile(r"^(\s*)tag nist:\s*\[(.*)\]\s*$")
KSI_LINE = re.compile(r"^\s*tag ksi(?:_broader|_unmapped)?:")
QUOTED = re.compile(r"'([^']+)'")


def safe_write(path: pathlib.Path, text: str) -> None:
    """Write, refusing any destination outside the repository.

    Today every path here comes from a glob under `controls/` or from a module
    constant, so nothing externally supplied reaches it. The guard is close to
    free, it mirrors `safe_path` in tools/test_evidence.py so the two tools
    handle this the same way, and it means a later caller that DOES take a
    destination from somewhere else cannot quietly turn a documentation
    generator into an arbitrary-write primitive.
    """
    resolved = path.resolve()
    if not resolved.is_relative_to(ROOT):
        raise SystemExit(f"refusing to write outside the repository: {path}")
    resolved.write_text(text)


def rewrite(text: str, catalog: KsiCatalog, path: pathlib.Path) -> str:
    out: list[str] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        out.append(line)
        i += 1

        match = NIST_LINE.match(line)
        if not match:
            continue

        indent, body = match.groups()
        tags = QUOTED.findall(body)
        if not tags:
            raise SystemExit(f"{path}: `tag nist:` with no control ids on line {i}")

        # Drop whatever KSI tags are currently there; they are regenerated
        # below. Done by consuming the following lines rather than by editing
        # them in place so that adding or removing a tier is not a special case.
        while i < len(lines) and KSI_LINE.match(lines[i]):
            i += 1

        try:
            resolution = catalog.resolve(tags)
        except ValueError as exc:
            raise SystemExit(f"{path}: {exc}") from exc
        out.extend(tag_lines(resolution, indent))

    return "\n".join(out) + "\n"


def collect() -> list[tuple[str, list[str]]]:
    """(control id, its NIST tags) for every control file, generated ones too.

    The document describes the whole profile, so it reads coverage.rb as well —
    unlike the rewrite pass, which must leave that file to its own generator.
    """
    found: list[tuple[str, list[str]]] = []
    for path in sorted(CONTROLS.glob("*.rb")):
        current = None
        for line in path.read_text().splitlines():
            match = CONTROL_ID.match(line)
            if match:
                current = match.group(1)
                continue
            match = NIST_LINE.match(line)
            if match and current:
                found.append((current, QUOTED.findall(match.group(2))))
                current = None
    return found


def _short(ksi_id: str) -> str:
    """`KSI-CMT-LMC` -> `LMC`, for the per-family summary column."""
    return ksi_id.rsplit("-", 1)[-1]


def _tally(catalog: KsiCatalog) -> tuple[dict, dict, dict]:
    """Which controls reach each KSI, reach it only weakly, or reach nothing.

    Reads every control file including the generated one: the document
    describes the whole profile, unlike the rewrite pass, which must leave
    coverage.rb to its own generator.
    """
    reached: dict[str, list[str]] = collections.defaultdict(list)
    broader: dict[str, list[str]] = collections.defaultdict(list)
    unmapped: dict[str, list[str]] = collections.defaultdict(list)

    for control_id, tags in collect():
        resolution = catalog.resolve(tags)
        for ksi_id in resolution.ksi:
            reached[ksi_id].append(control_id)
        for ksi_id in resolution.broader:
            broader[ksi_id].append(control_id)
        for control in resolution.unmapped:
            unmapped[control].append(control_id)

    return reached, broader, unmapped


def _family_table(catalog: KsiCatalog, reached: dict, broader: dict) -> list[str]:
    rows = [
        "## By indicator family",
        "",
        "| Family | | Reached | Indicators reached | Reached only as `ksi_broader` |",
        "|---|---|---|---|---|",
    ]
    total = 0
    for family in sorted(catalog.families):
        indicators = sorted(
            k for k, v in catalog.indicators.items() if v["family"] == family
        )
        hit = [k for k in indicators if k in reached]
        weak = [k for k in indicators if k in broader and k not in reached]
        total += len(hit)
        rows.append(
            f"| `{family}` | {catalog.families[family]['name']} | "
            f"{len(hit)}/{len(indicators)} | "
            f"{', '.join(_short(k) for k in hit) or '—'} | "
            f"{', '.join(_short(k) for k in weak) or '—'} |"
        )
    rows.append(f"| | **Total** | **{total}/{len(catalog.indicators)}** | | |")
    return rows


def _indicator_table(catalog: KsiCatalog, reached: dict) -> list[str]:
    rows = [
        "",
        "## Indicators this profile reaches",
        "",
        "The control count is how many controls carry the tag, not a strength "
        "score — one control asserting a thing well beats six asserting it "
        "loosely.",
        "",
        "| Indicator | | Controls |",
        "|---|---|---|",
    ]
    rows += [
        f"| `{ksi_id}` | {catalog.indicators[ksi_id]['name']} | "
        f"{len(reached[ksi_id])} |"
        for ksi_id in sorted(reached)
    ]
    return rows


def _gap_table(unmapped: dict) -> list[str]:
    rows = ["", "## NIST controls with no indicator", ""]
    if not unmapped:
        rows.append("None — every NIST control tagged in this profile reaches "
                    "an indicator.")
        return rows
    rows += [
        "No indicator cites these, or any enhancement of them. They are "
        "tagged `ksi_unmapped` on the controls listed, so the absence is "
        "visible in HDF rather than inferred from a missing tag.",
        "",
        "| Control | Tagged on |",
        "|---|---|",
    ]
    rows += [
        f"| `{control}` | "
        f"{', '.join(f'`{c}`' for c in sorted(set(unmapped[control])))} |"
        for control in sorted(unmapped)
    ]
    return rows


def render_doc(catalog: KsiCatalog) -> str:
    reached, broader, unmapped = _tally(catalog)
    src = catalog.source
    out = [
        DOC_BEGIN,
        "",
        f"Generated by `tools/render_ksi.py` from **{src['name']} "
        f"{src['version']}** against {len(collect())} controls. "
        "Do not edit by hand.",
        "",
    ]
    out += _family_table(catalog, reached, broader)
    out += _indicator_table(catalog, reached)
    out += _gap_table(unmapped)
    out += ["", DOC_END]
    return "\n".join(out)


def splice(current: str, block: str) -> str:
    start = current.find(DOC_BEGIN)
    end = current.find(DOC_END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"{DOC.name} is missing the {DOC_BEGIN} / {DOC_END} markers; "
            "add them first."
        )
    return current[:start] + block + current[end + len(DOC_END):]


def _targets() -> list[pathlib.Path]:
    return sorted(p for p in CONTROLS.glob("*.rb") if p.name not in GENERATED)


def _report_stale(stale: list[pathlib.Path], doc_stale: bool) -> int:
    """Print what is out of date, as annotations, and return the exit code."""
    for path in stale:
        print(
            f"::error file={path.relative_to(ROOT)}::KSI tags are stale — "
            "run `python3 tools/render_ksi.py`",
            file=sys.stderr,
        )
    if doc_stale:
        print(
            f"::error file={DOC.relative_to(ROOT)}::KSI coverage table is "
            "stale — run `python3 tools/render_ksi.py`",
            file=sys.stderr,
        )
    return 1 if (stale or doc_stale) else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if anything is out of date",
    )
    args = parser.parse_args()

    catalog = KsiCatalog()
    targets = _targets()
    if not targets:
        # An empty target list would make --check pass having verified nothing.
        print("::error::no hand-written control files found", file=sys.stderr)
        return 1

    pending = [(path, rewrite(path.read_text(), catalog, path)) for path in targets]
    pending = [(path, text) for path, text in pending if text != path.read_text()]

    # The document is rendered from the SAME resolution the tags came from, and
    # checked alongside them, so a stale document is as loud as a stale tag —
    # documentation that overstates coverage is worse than none.
    doc_current = DOC.read_text()
    doc_updated = splice(doc_current, render_doc(catalog))
    doc_stale = doc_updated != doc_current

    if args.check:
        rc = _report_stale([path for path, _ in pending], doc_stale)
        if rc == 0:
            print(f"KSI tags and coverage table in sync across {len(targets)} "
                  f"control files "
                  f"({catalog.source['name']} {catalog.source['version']}).")
        return rc

    changed = [path for path, _ in pending]
    for path, text in pending:
        safe_write(path, text)
    if doc_stale:
        safe_write(DOC, doc_updated)
        changed.append(DOC)

    for path in changed:
        print(f"rewrote {path.relative_to(ROOT)}")
    print(f"{len(changed)} file(s) changed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
