#!/usr/bin/env python3
"""Write `tag ksi:` into the hand-written control files, derived from `tag nist:`.

Why the tags are written into the source rather than computed
------------------------------------------------------------
InSpec collects `tag` values from the AST at PARSE time. A tag whose value is a
method call arrives at the collector as a RuboCop::AST::SendNode and it calls
`.value` on it:

    undefined method 'value' for an instance of RuboCop::AST::SendNode

That aborts `check` for the whole profile. So this cannot be a runtime lookup,
however much tidier that would read. It has to be a literal in the file, which
means something has to put it there and something has to prove it stayed
correct. This script is both: it rewrites in place, and `--check` fails when the
file disagrees with the mapping.

Scope
-----
The hand-written control files only. `controls/coverage.rb` is generated by
tools/render_controls.py, which emits its own KSI tags through the same
resolver — rewriting it here would put the two generators in a fight, each
undoing the other, and `--check` would flap depending on run order.

It also renders the generated block in docs/ksi_coverage.md, from the same
resolution, so the documented coverage and the emitted tags cannot disagree.

Usage:
    python3 tools/render_ksi.py            # rewrite in place
    python3 tools/render_ksi.py --check    # exit 1 if anything is stale
"""

from __future__ import annotations

import argparse
import collections
import pathlib
import re
import sys

from ksi_resolver import KsiCatalog, tag_lines

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTROLS = ROOT / "controls"
DOC = ROOT / "docs" / "ksi_coverage.md"
DOC_BEGIN = "<!-- BEGIN GENERATED: ksi-coverage -->"
DOC_END = "<!-- END GENERATED: ksi-coverage -->"

# Generated elsewhere from the same resolver. See the module docstring.
GENERATED = {"coverage.rb"}

# The ONLY value in this tool that originates outside the source: a filename
# read from the directory. Every write destination is rebuilt from module
# constants plus a name that has matched this, so nothing off the filesystem is
# ever spliced into a path.
SAFE_NAME = re.compile(r"[a-z][a-z0-9_]*\.rb")

CONTROL_ID = re.compile(r"^control\s+'([^']+)'\s+do\s*$")
NIST_LINE = re.compile(r"^(\s*)tag nist:\s*\[(.*)\]\s*$")
KSI_LINE = re.compile(r"^\s*tag ksi(?:_broader|_unmapped)?:")
QUOTED = re.compile(r"'([^']+)'")


def write_control(name: str, text: str) -> pathlib.Path:
    """Write one control file, addressed by validated name rather than by path.

    `name` is matched against SAFE_NAME and then joined to a module constant, so
    the destination is built entirely from values in this file. Passing the
    globbed `Path` straight through would mean a directory entry chose where the
    write landed; that is fine today and is not a property worth relying on in a
    tool whose whole job is to rewrite source files in place.

    The containment assertion stays as a second line of defence — cheap, and it
    mirrors `safe_path` in tools/test_evidence.py so both tools behave alike.
    """
    if not SAFE_NAME.fullmatch(name):
        raise SystemExit(f"refusing to write unexpected control filename: {name!r}")
    target = (CONTROLS / name).resolve()
    if not target.is_relative_to(ROOT):
        raise SystemExit(f"refusing to write outside the repository: {name!r}")
    target.write_text(text)
    return target


def write_doc(text: str) -> pathlib.Path:
    """Write the generated coverage document. Destination is a constant."""
    DOC.resolve().write_text(text)
    return DOC


def rewrite(text: str, catalog: KsiCatalog, where: str) -> str:
    """Return `text` with its `tag ksi*:` lines regenerated.

    `where` is a label for error messages only — never a path that gets opened,
    so a malformed control file cannot influence where anything is written.

    KSI lines are stripped from the whole file first and then re-emitted after
    each `tag nist:`. The earlier version consumed only the lines immediately
    following the NIST tag, which made it position-dependent: any tag written
    between the two — `tag nist_r4_unmapped:`, for instance — hid the existing
    KSI lines from the pass, which then wrote a second copy. That is not
    theoretical; it duplicated the tag across 28 controls once already.
    """
    # Every `tag ksi*:` line is generated by this tool, so the whole set can be
    # dropped and rebuilt. Removing them wherever they sit — rather than only
    # where they are expected to sit — is what makes a second run a no-op.
    lines = [line for line in text.splitlines() if not KSI_LINE.match(line)]

    out: list[str] = []
    for number, line in enumerate(lines, start=1):
        out.append(line)

        match = NIST_LINE.match(line)
        if not match:
            continue

        indent, body = match.groups()
        tags = QUOTED.findall(body)
        if not tags:
            raise SystemExit(f"{where}: `tag nist:` with no control ids on line {number}")

        try:
            resolution = catalog.resolve(tags)
        except ValueError as exc:
            raise SystemExit(f"{where}: {exc}") from exc
        out.extend(tag_lines(resolution, indent))

    return "\n".join(out) + "\n"


def collect() -> list[tuple[str, list[str]]]:
    """(control id, its NIST tags) for every control file, generated ones too.

    The document describes the whole profile, so it reads coverage.rb as well —
    unlike the rewrite pass, which must leave that file to its own generator.
    """
    found: list[tuple[str, list[str]]] = []
    for path in sorted(CONTROLS.glob("*.rb")):
        current = None
        for line in path.read_text().splitlines():
            match = CONTROL_ID.match(line)
            if match:
                current = match.group(1)
                continue
            match = NIST_LINE.match(line)
            if match and current:
                found.append((current, QUOTED.findall(match.group(2))))
                current = None
    return found


def _short(ksi_id: str) -> str:
    """`KSI-CMT-LMC` -> `LMC`, for the per-family summary column."""
    return ksi_id.rsplit("-", 1)[-1]


def _tally(catalog: KsiCatalog) -> tuple[dict, dict, dict]:
    """Which controls reach each KSI, reach it only weakly, or reach nothing.

    Reads every control file including the generated one: the document
    describes the whole profile, unlike the rewrite pass, which must leave
    coverage.rb to its own generator.
    """
    reached: dict[str, list[str]] = collections.defaultdict(list)
    broader: dict[str, list[str]] = collections.defaultdict(list)
    unmapped: dict[str, list[str]] = collections.defaultdict(list)

    for control_id, tags in collect():
        resolution = catalog.resolve(tags)
        for ksi_id in resolution.ksi:
            reached[ksi_id].append(control_id)
        for ksi_id in resolution.broader:
            broader[ksi_id].append(control_id)
        for control in resolution.unmapped:
            unmapped[control].append(control_id)

    return reached, broader, unmapped


def _family_table(catalog: KsiCatalog, reached: dict, broader: dict) -> list[str]:
    rows = [
        "## By indicator family",
        "",
        "| Family | | Reached | Indicators reached | Reached only as `ksi_broader` |",
        "|---|---|---|---|---|",
    ]
    total = 0
    for family in sorted(catalog.families):
        indicators = sorted(
            k for k, v in catalog.indicators.items() if v["family"] == family
        )
        hit = [k for k in indicators if k in reached]
        weak = [k for k in indicators if k in broader and k not in reached]
        total += len(hit)
        rows.append(
            f"| `{family}` | {catalog.families[family]['name']} | "
            f"{len(hit)}/{len(indicators)} | "
            f"{', '.join(_short(k) for k in hit) or '—'} | "
            f"{', '.join(_short(k) for k in weak) or '—'} |"
        )
    rows.append(f"| | **Total** | **{total}/{len(catalog.indicators)}** | | |")
    return rows


def _indicator_table(catalog: KsiCatalog, reached: dict) -> list[str]:
    rows = [
        "",
        "## Indicators this profile reaches",
        "",
        "The control count is how many controls carry the tag, not a strength "
        "score — one control asserting a thing well beats six asserting it "
        "loosely.",
        "",
        "| Indicator | | Controls |",
        "|---|---|---|",
    ]
    rows += [
        f"| `{ksi_id}` | {catalog.indicators[ksi_id]['name']} | "
        f"{len(reached[ksi_id])} |"
        for ksi_id in sorted(reached)
    ]
    return rows


def _gap_table(unmapped: dict) -> list[str]:
    rows = ["", "## NIST controls with no indicator", ""]
    if not unmapped:
        rows.append("None — every NIST control tagged in this profile reaches "
                    "an indicator.")
        return rows
    rows += [
        "No indicator cites these, or any enhancement of them. They are "
        "tagged `ksi_unmapped` on the controls listed, so the absence is "
        "visible in HDF rather than inferred from a missing tag.",
        "",
        "| Control | Tagged on |",
        "|---|---|",
    ]
    rows += [
        f"| `{control}` | "
        f"{', '.join(f'`{c}`' for c in sorted(set(unmapped[control])))} |"
        for control in sorted(unmapped)
    ]
    return rows


def render_doc(catalog: KsiCatalog) -> str:
    reached, broader, unmapped = _tally(catalog)
    src = catalog.source
    out = [
        DOC_BEGIN,
        "",
        f"Generated by `tools/render_ksi.py` from **{src['name']} "
        f"{src['version']}** against {len(collect())} controls. "
        "Do not edit by hand.",
        "",
    ]
    out += _family_table(catalog, reached, broader)
    out += _indicator_table(catalog, reached)
    out += _gap_table(unmapped)
    out += ["", DOC_END]
    return "\n".join(out)


def splice(current: str, block: str) -> str:
    start = current.find(DOC_BEGIN)
    end = current.find(DOC_END)
    if start == -1 or end == -1:
        raise SystemExit(
            f"{DOC.name} is missing the {DOC_BEGIN} / {DOC_END} markers; "
            "add them first."
        )
    return current[:start] + block + current[end + len(DOC_END):]


def _targets() -> list[str]:
    """Hand-written control-file NAMES, each validated on the way out."""
    names = []
    for entry in sorted(CONTROLS.glob("*.rb")):
        if entry.name in GENERATED:
            continue
        if not SAFE_NAME.fullmatch(entry.name):
            raise SystemExit(f"unexpected control filename: {entry.name!r}")
        names.append(entry.name)
    return names


def _report_stale(stale: list[str], doc_stale: bool) -> int:
    """Print what is out of date, as annotations, and return the exit code."""
    for name in stale:
        print(
            f"::error file=controls/{name}::KSI tags are stale — "
            "run `python3 tools/render_ksi.py`",
            file=sys.stderr,
        )
    if doc_stale:
        print(
            f"::error file={DOC.relative_to(ROOT)}::KSI coverage table is "
            "stale — run `python3 tools/render_ksi.py`",
            file=sys.stderr,
        )
    return 1 if (stale or doc_stale) else 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; exit 1 if anything is out of date",
    )
    args = parser.parse_args()

    catalog = KsiCatalog()
    targets = _targets()
    if not targets:
        # An empty target list would make --check pass having verified nothing.
        print("::error::no hand-written control files found", file=sys.stderr)
        return 1

    pending = []
    for name in targets:
        current = (CONTROLS / name).read_text()
        updated = rewrite(current, catalog, name)
        if updated != current:
            pending.append((name, updated))

    # The document is rendered from the SAME resolution the tags came from, and
    # checked alongside them, so a stale document is as loud as a stale tag —
    # documentation that overstates coverage is worse than none.
    doc_current = DOC.read_text()
    doc_updated = splice(doc_current, render_doc(catalog))
    doc_stale = doc_updated != doc_current

    if args.check:
        rc = _report_stale([name for name, _ in pending], doc_stale)
        if rc == 0:
            print(f"KSI tags and coverage table in sync across {len(targets)} "
                  f"control files "
                  f"({catalog.source['name']} {catalog.source['version']}).")
        return rc

    changed = [f"controls/{name}" for name, _ in pending]
    for name, text in pending:
        write_control(name, text)
    if doc_stale:
        write_doc(doc_updated)
        changed.append(str(DOC.relative_to(ROOT)))

    for label in changed:
        print(f"rewrote {label}")
    print(f"{len(changed)} file(s) changed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
